name: Build .NET MAUI App

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

env:
  WORKDIR: ".Net App/9.0/Tutorials/CreateNetMauiApp/code"
  SLN: "Notes.sln"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install MAUI workloads (Windows)
        run: |
          dotnet workload install maui maui-windows
          dotnet workload list

      - name: Restore
        run: dotnet restore "${{ env.SLN }}"
        working-directory: ${{ env.WORKDIR }}

      - name: Build (Release)
        run: dotnet build "${{ env.SLN }}" -c Release --no-restore
        working-directory: ${{ env.WORKDIR }}
