jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: "8.0.x" }

      - name: Install MAUI workloads (Windows)
        run: dotnet workload install maui maui-windows

      - name: Find MAUI project file
        id: findproj
        shell: pwsh
        run: |
          $proj = Get-ChildItem -Recurse -Filter *.csproj | Where-Object { $_.FullName -match 'Notes\.csproj' } | Select-Object -First 1
          if (-not $proj) { $proj = Get-ChildItem -Recurse -Filter *.csproj | Select-Object -First 1 }
          if (-not $proj) { throw "No .csproj found." }
          echo "PROJ=$($proj.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Restore
        run: dotnet restore "$env:PROJ"

      - name: Build
        run: dotnet build "$env:PROJ" -c Release --no-restore
